# lua-widow-control
# https://github.com/gucci-on-fleek/lua-widow-control
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2022 Max Chernoff

name: Build, Test, and Bundle

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Test, and Bundle
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: >
          (sudo apt-get update &&
          sudo apt-get install --no-install-recommends -y
          poppler-utils
          xsltproc
          ) & disown

      # From https://github.com/zauguin/install-texlive
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid

      # From https://github.com/zauguin/install-texlive
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
              ~/texlive
              ~/lmtx
          key: tex-v1-${{ steps.get-id.outputs.id }}
          restore-keys: tex-v1-

      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          packages: >
            collection-latexrecommended
            latex-bin-dev
            context
            l3build
            blindtext
            dejavu-otf
            kantlipsum
            linebreaker
            luatexbase
            optex

      - name: Install ConTeXt LMTX
        run: |
            if [ ! -d ~/lmtx ]; then
                mkdir ~/lmtx
                cd ~/lmtx
                wget http://lmtx.pragma-ade.nl/install-lmtx/context-linux-64.zip
                unzip context-linux-64.zip
                rm context-linux-64.zip
                chmod +x ./install.sh
            fi

            cd ~/lmtx
            ./install.sh

      - name: Set environment variables
        run: |
            echo "lmtx_context=$HOME/lmtx/tex/texmf-linux-64/bin/context" >> $GITHUB_ENV
            echo "tl_context=$HOME/texlive/bin/x86_64-linux/context" >> $GITHUB_ENV
            echo "TEXMFHOME=$GITHUB_WORKSPACE/texmf" >> $GITHUB_ENV

      - name: Build Documentation
        run: |
            cd "$GITHUB_WORKSPACE"
            l3build doc "$lmtx_context"

      - name: Test the package
        run: |
            # Temporary workaround; see latex3/l3build#232
            sed -i '/TEXMFCNF/,+2d' "$(kpsewhich l3build-check.lua)"
            export TEXMFHOME="$GITHUB_WORKSPACE/texmf"

            l3build check --show-log-on-error

      - name: Bundle the package
        run: |
          l3build bundle

      - name: Generate Release
        uses: ncipollo/release-action@v1
        if: "! ${{github.base_ref}}" # not a PR
        with:
          prerelease: true
          artifacts: ./lua-widow-control.tds.zip, ./lua-widow-control.ctan.zip, ./texmf/doc/luatex/lua-widow-control/lua-widow-control.pdf
          tag: release-${{github.sha}}
          commit: ${{github.sha}}
          name: Prerelease ${{github.sha}}
          body: |
            Automatically generated release for ${{github.sha}}

            > Lua-widow-control is a Plain TeX/LaTeX/ConTeXt/OpTeX package that removes widows and orphans without any user intervention. Using the power of LuaTeX, it does so _without_ stretching any glue or shortening any pages. Instead, lua-widow-control automatically lengthens a paragraph on a page where a widow or orphan would otherwise occur.

            Please note that this is a **prerelease** version of lua-widow-control. Most users should use the [latest release](https://github.com/gucci-on-fleek/lua-widow-control/releases/latest).

            ---

            `lua-widow-control.tds.zip` is a [TDS](https://texdoc.org/serve/tds/0) archive that is designed to be unpacked directly in your `TEXMF/` directory tree. `lua-widow-control.pdf` is the compiled package documentation. `lua-widow-control.ctan.zip` is an archive designed to be uploaded to [CTAN](https://www.ctan.org/help/upload-pkg) by the author (me). `test-results.zip` is a zip archive containing the results of the automated tests.
