# lua-widow-control
# https://github.com/gucci-on-fleek/lua-widow-control
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2022 Max Chernoff

name: Build, Test, and Bundle

on:
  - push
  - workflow_dispatch
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Test, and Bundle
    steps:
      - name: Pull Docker Images
        run: >
          docker pull contextgarden/context:lmtx &
          docker pull texlive/texlive:latest &

      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Build Documentation
        run: >
          docker run 
          -v "$GITHUB_WORKSPACE":/mnt
          -e TEXMFHOME=/mnt/texmf
          contextgarden/context:lmtx
          /bin/sh -c '
            sed -i "s/detokenize/luadetokenize/;/starttexdefinition externalfilter@process_inline/i\\\\\\def\\\luadetokenize\\{\\\ctxlua\\{tex.sprint\\(-2\\,\\ token.scanargument\\(false\\):gsub\\(\"\\\\\\\\(\\[A-Za-z\\]+\\)\\ \"\\,\\ \"\\\\\\\\\"\\ ..\\ string.char\\(37\\)\\ ..\\ \"1\"\\)\\ ..\\ \"\"\\)\\}\\}" /context/tex/texmf-modules/tex/context/third/filter/t-filter.mkxl;
            mtxrun --generate;
            cd /mnt/tests/ &&
            context --once ./context-basic.tex | grep === | diff -ws ./expected-results.txt - ||
            { echo "::error::ConTeXt LMTX Test Failed!"; exit 1; } &&
            cd /mnt/docs;
            mkdir ./tmp/ &&
            context lwc-documentation.tex
          '

      - name: Test the package under TeXLive
        run: >
          docker run
          -v "$GITHUB_WORKSPACE":/mnt
          -e TEXMFHOME=/mnt/texmf
          texlive/texlive:latest
          /bin/sh -c '
            mktexlsr &&
            mtxrun --generate &
            cd /mnt/tests/ &&
            lualatex-dev --halt-on-error ./latex-basic.tex | grep === | diff -ws /mnt/tests/expected-results.txt - ||
            { echo "::error::LaTeX Basic Test Failed!"; exit 1; } &&
            lualatex-dev --halt-on-error ./latex-advanced.tex &&
            lualatex-dev --halt-on-error ./latex-advanced.tex ||
            { echo "::error::LaTeX Advanced Test Failed!"; exit 1; } &&
            luatex --halt-on-error ./plain-basic.tex | grep === | diff -ws /mnt/tests/expected-results.txt - ||
            { echo "::error::Plain TeX Basic Test Failed!"; exit 1; } &&
            luatex --halt-on-error ./plain-columns.tex ||
            { echo "::error::Plain TeX Columns Test Failed!"; exit 1; } &&
            lualatex-dev --halt-on-error ./latex-columns.tex ||
            { echo "::error::LaTeX Columns Test Failed!"; exit 1; }
            optex --halt-on-error ./optex-basic.tex | grep === | diff -ws /mnt/tests/expected-results.txt - ||
            { echo "::error::OpTeX Basic Test Failed!"; exit 1; } &&
            context --once ./context-basic.tex | grep === | diff -ws ./expected-results.txt - ||
            { echo "::error::ConTeXt MKIV Test Failed!"; exit 1; }
          '

      - name: Bundle the package
        run: |
          cd "$GITHUB_WORKSPACE"/texmf
          zip -r "$GITHUB_WORKSPACE"/lua-widow-control.tds.zip ./*
          mkdir "$GITHUB_WORKSPACE"/ctan && cd "$GITHUB_WORKSPACE"/ctan
          mkdir lua-widow-control
          find -L "$GITHUB_WORKSPACE"/texmf -type f -exec cp '{}' lua-widow-control \;
          cp "$GITHUB_WORKSPACE"/lua-widow-control.tds.zip .
          zip -r "$GITHUB_WORKSPACE"/lua-widow-control.ctan.zip ./*
          cd "$GITHUB_WORKSPACE"/tests
          zip test-results.zip *.pdf *.log

      - name: Generate Release
        uses: ncipollo/release-action@v1
        if: "! ${{github.base_ref}}" # not a PR
        with:
          prerelease: true
          artifacts: ./lua-widow-control.tds.zip, ./lua-widow-control.ctan.zip, ./texmf/doc/luatex/lua-widow-control/lua-widow-control.pdf, ./tests/test-results.zip
          tag: release-${{github.sha}}
          commit: ${{github.sha}}
          name: Prerelease ${{github.sha}}
          body: |
            Automatically generated release for ${{github.sha}}  

            > Lua-widow-control is a Plain TeX/LaTeX/ConTeXt/OpTeX package that removes widows and orphans without any user intervention. Using the power of LuaTeX, it does so _without_ stretching any glue or shortening any pages. Instead, lua-widow-control automatically lengthens a paragraph on a page where a widow or orphan would otherwise occur.

            Please note that this is a **prerelease** version of lua-widow-control. Most users should use the [latest release](https://github.com/gucci-on-fleek/lua-widow-control/releases/latest).

            ---

            `lua-widow-control.tds.zip` is a [TDS](https://texdoc.org/serve/tds/0) archive that is designed to be unpacked directly in your `TEXMF/` directory tree. `lua-widow-control.pdf` is the compiled package documentation. `lua-widow-control.ctan.zip` is an archive designed to be uploaded to [CTAN](https://www.ctan.org/help/upload-pkg) by the author (me). `test-results.zip` is a zip archive containing the results of the automated tests.
